### ISSUE TITLE
You are not currently on a branch.

### ISSUE THREAD

**Issue by rawkode** [TriPSs/conventional-changelog-action#107]
Hi,

I'm not sure what I'm doing wrong, I think there's maybe a bug?

My release workflow logs:
- https://github.com/comtrya/comtrya/runs/2153204192?check_suite_focus=true

```
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

(node:1600) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/git' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:574:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:557:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:451:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:1600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TriPSs** [comment]
I think it's because the work flow is triggered on a tag instead of a branch.

**Comment by rawkode** [comment]
I would imagine updating the release with a changelog is a rather common operation for an action like this, so could it be supported?

**Comment by TriPSs** [comment]
Sorry I don't see this supported, the action creates the tag itself so it can probably determine the changes.
