### ISSUE TITLE
Unhandled promise rejection if tag exists

### ISSUE THREAD

**Issue by dgusakov** [TriPSs/conventional-changelog-action#173]
## Problem
When running action we get unhandled promise rejection when tag already exist
`fatal: tag '1.51.0' already exists
(node:1595) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/git' failed with exit code 128
    at ExecState._setResult (/home/runner/work/_actions/lidofinance/conventional-changelog-action/v3.11.0/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/lidofinance/conventional-changelog-action/v3.11.0/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/lidofinance/conventional-changelog-action/v3.11.0/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)`
At the same time action completes successfully with no outputs set.

 ## Possible solution
 We can add
 `process.on('unhandledRejection', (reason, promise) => {
  console.log('Unhandled Rejection at:', promise, 'reason:', reason);
  core.setFailed(reason);
});`
So that all unhandled rejections will result in action failure

**Comment by dgusakov** [comment]
@TriPSs Should I submit PR?

**Comment by TriPSs** [comment]
Yes that would be a good one, thanks!
