### ISSUE TITLE
Error after the action commits new version tag

### ISSUE THREAD

**Issue by Tormak9970** [TriPSs/conventional-changelog-action#208]
I have the following workflow file: [found here](https://github.com/Tormak9970/Steam-Art-Manager/blob/release/.github/workflows/release.yml)

When I trigger it it runs fine until it gets to the end (based on looking at the action's index.js looks like it might be when the git push occurs) I get this: 
```
New version: 0.1.0
/usr/bin/git add .
/usr/bin/git commit -m chore(release): v0.1.0 [skip ci]
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean
Unhandled Rejection occurred. Error: The process '/usr/bin/git' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:469:27)
Error: Unhandled Rejection occurred. Error: The process '/usr/bin/git' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
```

**Comment by Tormak9970** [comment]
Also, is it possible to exclude "chore" commits from the change log?

**Comment by Tormak9970** [comment]
I managed to fix it by removing `skip-version-file: 'false'` but its failing to bump the package.json's version field
