### ISSUE TITLE
Error when running on self-hosted runners

### ISSUE THREAD

**Issue by apider** [TriPSs/conventional-changelog-action#216]
Hi,
great action!

Works great on GH supplied runners, but does not want to run on my self-hosted runners, neither standalone linux runner or ARC runners in k8s.

`Run TriPSs/conventional-changelog-action@v3
  with:
    github-token: ***
    git-message: chore(release): {version}
    git-user-name: Conventional Changelog Action
    git-user-email: conventional.changelog.action@github.com
    git-pull-method: --ff-only
    git-push: true
    git-branch: refs/heads/master
    preset: angular
    tag-prefix: v
    output-file: CHANGELOG.md
    release-count: 5
    version-file: ./package.json
    version-path: version
    skip-git-pull: false
    skip-on-empty: true
    skip-version-file: false
    skip-commit: false
    skip-tag: false
    git-url: github.com
    skip-ci: true
    create-summary: false
    pre-release: false
    pre-release-identifier: rc
  env:
    NODE_ENV: production
Using "angular" preset
Using "chore(release): {version} [skip ci]" as commit message
Using "Conventional Changelog Action" as git user.name
Using "conventional.changelog.action@github.com" as git user.email
Using "5" release count
Using "./package.json" as version file
Using "version" as version path
Using "v" as tag prefix
Using "CHANGELOG.md" as output file
Using "" as config file
Using "github.com" as gitUrl
Using "master" as gitBranch
Using "" as gitPath
Skipping empty releases is "enabled"
Skipping the update of the version file is "disabled"
/usr/bin/git config user.name Conventional Changelog Action
fatal: not in a git directory
Unhandled Rejection occurred. Error: The process '/usr/bin/git' failed with exit code 1[2](https://github.com/***/xxx/actions/runs/5113777712/jobs/9193352979#step:3:2)8
    at ExecState._setResult (/home/***/actions-runner-***/_work/_actions/TriPSs/conventional-changelog-action/v[3](https://github.com/***/xxx/actions/runs/5113777712/jobs/9193352979#step:3:3)/node_modules/@actions/exec/lib/toolrunner.js:592:25)
Error: Unhandled Rejection occurred. Error: The process '/usr/bin/git' failed with exit code 128
    at ExecState._setResult (/home/***/actions-runner-***/_work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/home/***/actions-runner-***/_work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/home/***/actions-runner-***/_work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:[4](https://github.com/***coding/xxx/actions/runs/5113777712/jobs/9193352979#step:3:4)69:27)
    at ChildProcess.emit (node:events:[5](https://github.com/***/xxx/actions/runs/5113777712/jobs/9193352979#step:3:5)27:28)
    at maybeClose (node:internal/child_process:1092:1[6](https://github.com/***/xxx/actions/runs/5113777712/jobs/9193352979#step:3:6))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at ExecState.CheckComplete (/home/***/actions-runner-***/_work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:5[7](https://github.com/***/xxx/actions/runs/5113777712/jobs/9193352979#step:3:7)5:1[8](https://github.com/***/xxx/actions/runs/5113777712/jobs/9193352979#step:3:8))
    at ChildProcess.<anonymous> (/home/***/actions-runner-***/_work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:46[9](https://github.com/***/xxx/actions/runs/5113777712/jobs/9193352979#step:3:9):27)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:[10](https://github.com/***/xxx/actions/runs/5113777712/jobs/9193352979#step:3:10)92:[16](https://github.com/***/xxx/actions/runs/5113777712/jobs/9193352979#step:3:16))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:[30](https://github.com/***/xxx/actions/runs/5113777712/jobs/9193352979#step:3:31)2:5)`

**Comment by apider** [comment]
Local runner version: `2.304.0`

**Comment by TriPSs** [comment]
Probably has to do with the following error out of your log:
> Changelog Action fatal: not in a git directory Unhandled Rejection occurred.
