### ISSUE TITLE
Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by visualcookie** [TriPSs/conventional-changelog-action#65]
Hej.

While trying to set up this action correctly, I run into the following issue:

```
Run TriPSs/conventional-changelog-action@master
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/TriPSs/conventional-changelog-action/master/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/master/src/index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/TriPSs/conventional-changelog-action/master/src/index.js'
  ]
}
```

**Comment by TriPSs** [comment]
Hi @visualcookie, plz use `uses: TriPSs/conventional-changelog-action@v3` instead of `@master`
